export const ADD_TO_SV = 'ADD_TO_SV';
export const DELETE_CATEGORIES_IN_SV = 'DELETE_CATEGORIES_IN_SV';
export const EDIT_CATEGORIES_IN_SV = 'EDIT_CATEGORIES_IN_SV';
export const UPDATE_CATEGORIES_IN_SV = 'UPDATE_CATEGORIES_IN_SV';
export const SHOWCATEGORIES = 'SHOWCATEGORIES';


